[tool.poetry]
name = "ia-and-dv"
version = "0.1.0"
description = "study project for master study course in SPBSTU"
authors = ["alexandr", "margaret", "julia"]
readme = "README.md"
exclude = [  ]
package-mode = false  # TODO: later should delete?


[tool.poetry.dependencies]
python = ">=3.12,<3.13"
jinja2 = "^3.1.5"
ipykernel = "^6.29.5"
taipy="4.1.0"
plotly = "^6.3.1"
clickhouse-connect = "^0.9.2"
mlflow = "^2.20.3"
shapiq = "^1.7.0"
shap = "^0.52.0"


[tool.poetry.group.dev-model]
optional=true


[tool.poetry.group.dev-model.dependencies]
python = ">=3.12,<3.13"


[tool.poetry.group.stage-model]
optional=true


[tool.poetry.group.stage-model.dependencies]
python = ">=3.12,<3.13"
mlflow = "^2.20.3"

[tool.poetry.group.dev.dependencies]
ruff = "0.3.0"
pre-commit = "3.6.2"
notebook = ">=7.1.2"
psutil = "^7.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.ruff]
lint.extend-select = ["W", "I", "NPY"]
lint.ignore = ["E741", "F841", "E722", "F821"]